export const mermaid = {
  theme: 'base',
  flowchart: {
    useMaxWidth: false,
    htmlLabels: true,
    curve: 'basis',
    nodeSpacing: 56,
    rankSpacing: 62,
  },
  themeVariables: {
    primaryColor: '#edf3ff',
    primaryTextColor: '#192333',
    primaryBorderColor: '#174ca6',
    secondaryColor: '#f8efe0',
    secondaryTextColor: '#192333',
    secondaryBorderColor: '#bb5e2b',
    tertiaryColor: '#e9f4ef',
    tertiaryTextColor: '#192333',
    tertiaryBorderColor: '#247156',
    lineColor: '#174ca6',
    textColor: '#192333',
    fontSize: '14px',
    fontFamily: 'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, sans-serif',
    clusterBkg: '#f4f0e7',
    clusterBorder: '#cbc5b9',
    titleColor: '#192333',
    edgeLabelBackground: '#fbf9f4',
  },
}
